version: '2.0'
services:
  hada_ws:
    build: .
    ports:
      - "5000:5000"
      # INIT_TYPE:
      # local: standalone mode, uses local configuration files and datasets
      # remote: uses the Data Exchange service for resources,
      #         expected to be reacheable at localhost:5333
    environment:
      - INIT_TYPE=remote
